#Wether or not gens can split
Gen-Splitter: true

#Gens that can split
#https://helpch.at/docs/1.8/org/bukkit/Material.html
Split-Spawners:
  - IRON_INGOT
  - GOLD_INGOT

#Overrides MBedwars' auto-pickup system
#The killer only receives this message if a victim has items
#Only Items that the victim had will be included in the list
#So it wont say Iron +0 or whatever
Auto-Collect:
  Enabled: true
  Message-Materials:
    - IRON_INGOT
    - GOLD_INGOT
    - DIAMOND
    - EMERALD
  Message: '%color%%item% &f+%amount%'

#How close players have to be together in order for items to split
#1.5 - 2.0 is recommended
Split-Radius: 1.5

#Prevents people from dropping items in the void when falling to their death
#This wont really effect anything unless MBedwars
#auto-collect (or Direct-Collect) is enabled
Anti-Void-Drops: false