version: 4.3.0
name: Gen-Splitter
author: MetallicGoat
main: me.metallicgoat.gensplitter.GenSplitterPlugin
api-version: 1.13
description: Gen Splitter for MBedwars
depend: [MBedwars, MBedwars-LevelShop]